services:
  postgres:
    image: postgres:18
    container_name: objetiva-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: objetiva
      POSTGRES_PASSWORD: objetiva
      POSTGRES_DB: objetiva
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data: